// Auto-generated by scripts/set-env.js during build
// Supports runtime override via window.__COLLABAI_CONFIG__ or build-time injected constants.

export const environment = {
  production: true,
  apiBaseUrl:
    (typeof window !== 'undefined' &&
      (window as any).__COLLABAI_CONFIG__?.apiBaseUrl) ||
    'https://collabai-api.onrender.com/api/v1',
  socketUrl:
    (typeof window !== 'undefined' &&
      (window as any).__COLLABAI_CONFIG__?.socketUrl) ||
    'https://collabai-api.onrender.com',
};
