// scripts/set-env.js
// Injects environment variables (API_BASE_URL / BACKEND_URL, SOCKET_URL)
// into src/environments/environment.prod.ts during Render or CI build.

const fs = require('fs');
const path = require('path');

const rawBackendUrl = process.env.BACKEND_URL || '';
const cleanBackend = rawBackendUrl.trim().replace(/\/$/, '');

const apiBaseUrl =
  process.env.API_BASE_URL?.trim() ||
  (cleanBackend ? `${cleanBackend}/api/v1` : '');

const socketUrl =
  process.env.SOCKET_URL?.trim() ||
  cleanBackend;

const envProdPath = path.join(__dirname, '../src/environments/environment.prod.ts');

const defaultApiBaseUrl = apiBaseUrl || '/api/v1';
const defaultSocketUrl = socketUrl || '';

const content = `// Auto-generated by scripts/set-env.js during build
// Supports runtime override via window.__COLLABAI_CONFIG__ or build-time injected constants.

export const environment = {
  production: true,
  apiBaseUrl:
    (typeof window !== 'undefined' &&
      (window as any).__COLLABAI_CONFIG__?.apiBaseUrl) ||
    '${defaultApiBaseUrl}',
  socketUrl:
    (typeof window !== 'undefined' &&
      (window as any).__COLLABAI_CONFIG__?.socketUrl) ||
    '${defaultSocketUrl}',
};
`;

try {
  fs.writeFileSync(envProdPath, content, 'utf8');
  console.log(`[set-env] Injected environment.prod.ts:`);
  console.log(`  - apiBaseUrl: ${defaultApiBaseUrl}`);
  console.log(`  - socketUrl:  ${defaultSocketUrl || '(none)'}`);
} catch (err) {
  console.error('[set-env] Failed to write environment.prod.ts:', err);
  process.exit(1);
}
